name: Tests

on: [ push ]

jobs:
  build:
    name: ${{matrix.operating-system}}, PHP ${{ matrix.php }}

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest, ubuntu-24.04 ]
        php: [ '8.4' ]

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GH_TOKEN }}"}}'

      - name: Run tests
        run: composer run tests
      
      - name: Run PHPStan
        run: composer run phpstan
      
      - name: Run PHPCS
        run: composer run phpcs